-- CLIENTES
INSERT INTO CLIENTE (ID_CLIENTE, NOME, CPF, EMAIL, SENHA, TELEFONE, ENDERECO) VALUES (SEQ_CLIENTE_ID.nextval, 'Otavio Baroni', '111.111.111-11', 'otavio@email.com', '123', '(16) 99911-1111', 'Rua 10, 100');
INSERT INTO CLIENTE (ID_CLIENTE, NOME, CPF, EMAIL, SENHA, TELEFONE, ENDERECO) VALUES (SEQ_CLIENTE_ID.nextval, 'Lucas Parila', '222.222.222-22', 'lucas@email.com', '456', '(16) 99922-2222', 'Rua 20, 200');
INSERT INTO CLIENTE (ID_CLIENTE, NOME, CPF, EMAIL, SENHA, TELEFONE, ENDERECO) VALUES (SEQ_CLIENTE_ID.nextval, 'Rafael Matias', '333.333.333-33', 'rafael@email.com', '789', '(16) 99933-3333', 'Rua 30, 300');
INSERT INTO CLIENTE (ID_CLIENTE, NOME, CPF, EMAIL, SENHA, TELEFONE, ENDERECO) VALUES (SEQ_CLIENTE_ID.nextval, 'Bruno Posar', '444.444.444-44', 'bruno@email.com', 'ABC', '(16) 99944-4444', 'Rua A, 400');
INSERT INTO CLIENTE (ID_CLIENTE, NOME, CPF, EMAIL, SENHA, TELEFONE, ENDERECO) VALUES (SEQ_CLIENTE_ID.nextval, 'Guilherme Siqueira', '555.555.555-55', 'guilherme@email.com', 'DEF', '(16) 99955-5555', 'Rua B, 50');

-- CONTAS
INSERT INTO CONTA (ID_CONTA, NUM_CONTA, AGENCIA, ID_CLIENTE, STATUS) VALUES (SEQ_CONTA_ID.nextval, '0001', '2531', 1, 'APROVADA');
INSERT INTO CONTA (ID_CONTA, NUM_CONTA, AGENCIA, ID_CLIENTE, STATUS) VALUES (SEQ_CONTA_ID.nextval, '0002', '2531', 2, 'APROVADA');
INSERT INTO CONTA (ID_CONTA, NUM_CONTA, AGENCIA, ID_CLIENTE, STATUS) VALUES (SEQ_CONTA_ID.nextval, '0003', '2531', 3, 'PENDENTE');
INSERT INTO CONTA (ID_CONTA, NUM_CONTA, AGENCIA, ID_CLIENTE, STATUS) VALUES (SEQ_CONTA_ID.nextval, '0004', '2531', 4, 'APROVADA');
INSERT INTO CONTA (ID_CONTA, NUM_CONTA, AGENCIA, ID_CLIENTE, STATUS) VALUES (SEQ_CONTA_ID.nextval, '0005', '2531', 5, 'PENDENTE');

-- TRANSFERÊNCIAS
INSERT INTO TRANSACAO (ID_TRANSACAO, NUM_CONTA, TIPO_TRANSACAO, VALOR, DESCRICAO) VALUES (SEQ_TRANSACAO_ID.nextval, 0001, 'DEPOSITO', 500.00, 'Depósito inicial');
INSERT INTO TRANSACAO (ID_TRANSACAO, NUM_CONTA, TIPO_TRANSACAO, VALOR, DESCRICAO) VALUES (SEQ_TRANSACAO_ID.nextval, 0001, 'SAQUE', 50.00, 'Saque ATM');
INSERT INTO TRANSACAO (ID_TRANSACAO, NUM_CONTA, TIPO_TRANSACAO, VALOR, DESCRICAO) VALUES (SEQ_TRANSACAO_ID.nextval, 0002, 'DEPOSITO', 1200.00, 'Salário');
INSERT INTO TRANSACAO (ID_TRANSACAO, NUM_CONTA, TIPO_TRANSACAO, VALOR, DESCRICAO) VALUES (SEQ_TRANSACAO_ID.nextval, 0004, 'TRANSFERENCIA', 150.00, 'Pagamento conta');
INSERT INTO TRANSACAO (ID_TRANSACAO, NUM_CONTA, TIPO_TRANSACAO, VALOR, DESCRICAO) VALUES (SEQ_TRANSACAO_ID.nextval, 0005, 'DEPOSITO', 300.00, 'Recarga de saldo');

-- Deverá ser feito com TRIGER ou PROCEDIMENTO)
UPDATE CONTA SET SALDO = 450.00 WHERE NUM_CONTA = 0001;
UPDATE CONTA SET SALDO = 1200.00 WHERE NUM_CONTA = 0002;
UPDATE CONTA SET SALDO = 150.00 WHERE NUM_CONTA = 0004;

COMMIT;

-- INVESTIMENTOS
INSERT INTO INVESTIMENTO (ID_INVEST, NUM_CONTA, NOME_INVEST, VALOR_APLICADO, RENTABILIDADE_PERCENT) VALUES (SEQ_INVESTIMENTO_ID.nextval, 0001, 'CDB Liquidez Diaria', 200.00, 10.50);
INSERT INTO INVESTIMENTO (ID_INVEST, NUM_CONTA, NOME_INVEST, VALOR_APLICADO, RENTABILIDADE_PERCENT) VALUES (SEQ_INVESTIMENTO_ID.nextval, 0002, 'LCI Isento', 500.00, 11.20);
INSERT INTO INVESTIMENTO (ID_INVEST, NUM_CONTA, NOME_INVEST, VALOR_APLICADO, RENTABILIDADE_PERCENT) VALUES (SEQ_INVESTIMENTO_ID.nextval, 0004, 'Tesouro Selic', 100.00, 9.80);
INSERT INTO INVESTIMENTO (ID_INVEST, NUM_CONTA, NOME_INVEST, VALOR_APLICADO, RENTABILIDADE_PERCENT) VALUES (SEQ_INVESTIMENTO_ID.nextval, 0001, 'Fundo Acoes', 300.00, 15.00);
INSERT INTO INVESTIMENTO (ID_INVEST, NUM_CONTA, NOME_INVEST, VALOR_APLICADO, RENTABILIDADE_PERCENT) VALUES (SEQ_INVESTIMENTO_ID.nextval, 0002, 'Previdencia XPTO', 1000.00, 8.00);

COMMIT;

INSERT INTO GERENTE (ID_GERENTE, NOME, EMAIL, SENHA) VALUES (SEQ_GERENTE_ID.nextval, 'Felipe Henrique', 'felipe@bitpay.com', 'gerente123');
INSERT INTO GERENTE (ID_GERENTE, NOME, EMAIL, SENHA) VALUES (SEQ_GERENTE_ID.nextval, 'Julia Moreira', 'julia@bitpay.com', 'gerente123');
INSERT INTO GERENTE (ID_GERENTE, NOME, EMAIL, SENHA) VALUES (SEQ_GERENTE_ID.nextval, 'Roberto Andrade', 'roberto@bitpay.com', 'gerente123');
INSERT INTO GERENTE (ID_GERENTE, NOME, EMAIL, SENHA) VALUES (SEQ_GERENTE_ID.nextval, 'Leticia Ribas', 'leticia@bitpay.com', 'gerente123');
INSERT INTO GERENTE (ID_GERENTE, NOME, EMAIL, SENHA) VALUES (SEQ_GERENTE_ID.nextval, 'Gustavo Hamad', 'gustavo@bitpay.com', 'gerente123');

COMMIT;

SELECT * FROM CLIENTE;
SELECT * FROM CONTA;
SELECT * FROM TRANSACAO;
SELECT * FROM INVESTIMENTO;
SELECT * FROM GERENTE;
