CREATE SEQUENCE SEQ_CLIENTE_ID
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE TABLE CLIENTE (
    ID_CLIENTE NUMBER(10) DEFAULT SEQ_CLIENTE_ID.NEXTVAL, 
    NOME VARCHAR2(100) NOT NULL,                      
    CPF VARCHAR2(14) NOT NULL UNIQUE,            
    EMAIL VARCHAR2(100) NOT NULL UNIQUE,
    TELEFONE VARCHAR2(20),
    ENDERECO VARCHAR2(255),
    SENHA VARCHAR2(55) NOT NULL,                      
    DATA_CADASTRO DATE DEFAULT SYSDATE,
    CONSTRAINT PK_CLIENTE PRIMARY KEY (ID_CLIENTE)          
);

CREATE SEQUENCE SEQ_CONTA_ID 
START WITH 1000 
INCREMENT BY 1 
NOCACHE 
NOCYCLE;

CREATE TABLE CONTA (
    ID_CONTA NUMBER(10) DEFAULT SEQ_CONTA_ID.NEXTVAL,
    NUM_CONTA NUMBER(10) NOT NULL UNIQUE,
    AGENCIA VARCHAR2(4) NOT NULL,
    SALDO NUMBER(15,2) DEFAULT 0.00 NOT NULL,
    ID_CLIENTE NUMBER(10) NOT NULL,
    DATA_ABERTURA DATE DEFAULT SYSDATE,
    STATUS VARCHAR2(20) DEFAULT 'PENDENTE' NOT NULL,
    CONSTRAINT FK_CONTA_CLIENTE FOREIGN KEY (ID_CLIENTE)    
        REFERENCES CLIENTE (ID_CLIENTE)
);

CREATE SEQUENCE SEQ_TRANSACAO_ID
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE TABLE TRANSACAO (
    ID_TRANSACAO NUMBER(10) DEFAULT SEQ_TRANSACAO_ID.NEXTVAL,
    NUM_CONTA NUMBER(10) NOT NULL,
    DATA_TRANS TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    TIPO_TRANS VARCHAR2(20) NOT NULL, 
    VALOR NUMBER(15,2) NOT NULL CHECK (VALOR > 0),
    DESCRICAO VARCHAR2(200),
    CONSTRAINT PK_TRANSACAO PRIMARY KEY (ID_TRANSACAO),
    CONSTRAINT FK_TRANSACAO_CONTA FOREIGN KEY (NUM_CONTA)
        REFERENCES CONTA (NUM_CONTA)
);