CREATE SEQUENCE SEQ_CLIENTE_ID
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE TABLE CLIENTE (
    ID_CLIENTE NUMBER DEFAULT SEQ_CLIENTE_ID.NEXTVAL, 
    NOME VARCHAR2(100) NOT NULL,                      
    CPF VARCHAR2(14) NOT NULL UNIQUE,            
    EMAIL VARCHAR2(100) NOT NULL UNIQUE,
    TELEFONE VARCHAR2(20),
    ENDERECO VARCHAR2(255),
    SENHA VARCHAR2(55) NOT NULL,                      
    DATA_CADASTRO DATE DEFAULT SYSDATE,
    CONSTRAINT PK_CLIENTE PRIMARY KEY (ID_CLIENTE)          
);

CREATE SEQUENCE SEQ_CONTA_ID 
START WITH 1000 
INCREMENT BY 1 
NOCACHE 
NOCYCLE;

CREATE TABLE CONTA (
    ID_CONTA NUMBER DEFAULT SEQ_CONTA_ID.NEXTVAL,
    NUM_CONTA NUMBER(10) NOT NULL UNIQUE,
    AGENCIA VARCHAR2(4) NOT NULL,
    SALDO NUMBER(15,2) DEFAULT 0.00 NOT NULL,
    ID_CLIENTE NUMBER(10) NOT NULL,
    DATA_ABERTURA DATE DEFAULT SYSDATE,
    STATUS VARCHAR2(20) DEFAULT 'PENDENTE' NOT NULL,
    CONSTRAINT FK_CONTA_CLIENTE FOREIGN KEY (ID_CLIENTE)    
        REFERENCES CLIENTE (ID_CLIENTE)
);

CREATE SEQUENCE SEQ_TRANSACAO_ID
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE TABLE TRANSACAO (
    ID_TRANSACAO NUMBER DEFAULT SEQ_TRANSACAO_ID.NEXTVAL,
    NUM_CONTA NUMBER(10) NOT NULL,
    DATA_TRANSACAO TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    TIPO_TRANSACAO VARCHAR2(20) NOT NULL, 
    VALOR NUMBER(15,2) NOT NULL CHECK (VALOR > 0),
    DESCRICAO VARCHAR2(200),
    CONSTRAINT PK_TRANSACAO PRIMARY KEY (ID_TRANSACAO),
    CONSTRAINT FK_TRANSACAO_CONTA FOREIGN KEY (NUM_CONTA)
        REFERENCES CONTA (NUM_CONTA)
);

CREATE SEQUENCE SEQ_INVESTIMENTO_ID
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE TABLE INVESTIMENTO (
    ID_INVEST NUMBER DEFAULT SEQ_INVESTIMENTO_ID.NEXTVAL,
    NUM_CONTA NUMBER(10) NOT NULL,
    NOME_INVEST  VARCHAR2(50) NOT NULL,
    VALOR_APLICADO NUMBER(15, 2)  NOT NULL CHECK (VALOR_APLICADO > 0),
    DATA_APLICACAO DATE DEFAULT SYSDATE NOT NULL,
    DATA_RESGATE DATE,
    RENTABILIDADE_PERCENT NUMBER(5, 2),
    CONSTRAINT PK_INVESTIMENTO PRIMARY KEY (ID_INVEST),
    CONSTRAINT FK_INVEST_CONTA FOREIGN KEY (NUM_CONTA)
        REFERENCES CONTA (NUM_CONTA)
);

CREATE SEQUENCE SEQ_GERENTE_ID
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE TABLE GERENTE (
    ID_GERENTE NUMBER DEFAULT SEQ_GERENTE_ID.NEXTVAL,
    NOME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL UNIQUE,
    SENHA VARCHAR2(64) NOT NULL,
    CONSTRAINT PK_GERENTE PRIMARY KEY (ID_GERENTE)
);
